server:
  port: 8999
    
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: user-service1
        uri: lb://user-service
        predicates:
        - Path=/user/**
      - id: contact-service
        uri: lb://contact-service
        predicates:
        - Path=/contact/**
            
                
        