server:
  port: 8999
    
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service           #this is spring service application name for user service MS 
        predicates:
        - Path=/user/**
      - id: contact-service
        uri: lb://contact-service          #this is spring service application name for contact service MS 
        predicates:
        - Path=/contact/**
            
                
        